import typescript from '@rollup/plugin-typescript';
const html = require('rollup-plugin-html');

export default {

  preserveModules: true,

  input: 'src/index.ts',

  output: {
    dir: 'dist',
    format: 'cjs'
  },

  plugins: [

    typescript(),

    html({
      htmlMinifierOptions: {
        collapseWhitespace: true,
        collapseInlineTagWhitespace: true,
        includeAutoGeneratedTags: false,
        minifyCSS: true,
        removeComments: true
      } 
    })

  ]
};